const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
const DECREASE_PRODUCT_FROM_BASKET = "DECREASE_PRODUCT_FROM_BASKET";
const REMOVE_ALL_PRODUCTS_FROM_BASKET = "REMOVE_ALL_PRODUCTS_FROM_BASKET";
const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
const DECREASE_PRODUCTS_FROM_BASKET = "DECREASE_PRODUCTS_FROM_BASKET";
const ADD_ALL_FAVORITES_TO_BASKET = "ADD_ALL_FAVORITES_TO_BASKET";

export {
  ADD_PRODUCT_TO_BASKET,
  DECREASE_PRODUCT_FROM_BASKET,
  REMOVE_ALL_PRODUCTS_FROM_BASKET,
  REMOVE_PRODUCT_FROM_BASKET,
  DECREASE_PRODUCTS_FROM_BASKET,
  ADD_ALL_FAVORITES_TO_BASKET,
};
