const SET_PRODUCTS = "SET_PRODUCTS";
const SORT_PRODUCTS_BY_HIGHER = "SORT_PRODUCTS_BY_HIGHER";
const SORT_PRODUCTS_BY_LOWEST = "SORT_PRODUCTS_BY_LOWEST";
const SORT_PRODUCTS_BY_CATEGORIES = "SORT_PRODUCTS_BY_CATEGORIES";
const SORT_PRODUCTS_BY_MAX_PRICE = "SORT_PRODUCTS_BY_MAX_PRICE";

export {
  SET_PRODUCTS,
  SORT_PRODUCTS_BY_HIGHER,
  SORT_PRODUCTS_BY_LOWEST,
  SORT_PRODUCTS_BY_CATEGORIES,
  SORT_PRODUCTS_BY_MAX_PRICE,
};
